device: "auto"

paths:
  text_emb_dir: "data/real/processed/embeddings/text"
  audio_emb_dir: "data/real/processed/embeddings/audio"
  npz_dir:  "data/real/processed/npz"
  ckpt_dir: "checkpoints/mapper_real"
  index_dir: "data/real/processed/index"
  paramreg_ckpt: "checkpoints/paramreg_v8/paramreg_best.pt"
  params_config: "configs/params_real.yaml"

normalize_embeddings: true

model:
  in_dim: 512
  hidden: [512, 512]
  out_dim: 512
  dropout: 0.10
  norm_out: true

train:
  seed: 42
  val_ratio: 0.2
  batch_size: 16
  epochs: 250
  lr: 0.001
  weight_decay: 0.00001
  early_stop_patience: 25

  loss: "cosine"
  lambda_embed: 0.3
  lambda_param: 0.70

  param_loss: "huber"
  param_beta: 0.02

  param_loss_weights:
    decay_t60: 2.0
    pitch_hz: 2.0
    brightness: 1.0
    damping: 1.2
    pick_position: 1.0
    noise_mix: 1.0
