# configs/synth.yaml
device: "cpu"

synth:
  type: "karplus_strong"  
  input_dim: 512
  hidden: [512, 512]      
  seconds: 1.0
  sample_rate: 16000

paths:
  mapper_ckpt: "checkpoints/mapper/mapper_best.pt"
  clap_ckpt: "checkpoints/clap/clap_630k.pt"
  output_dir: "outputs/gen_audio"
